"""requirement baselines and versions

Revision ID: b17c387ca429
Revises: cb3a5dae0416
Create Date: 2026-09-17 10:17:40.845086

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b17c387ca429"
down_revision = "cb3a5dae0416"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement_baselines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requirement_baselines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_baselines_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_baselines_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_requirement_baselines_project_status", ["project_id", "status"], unique=False
        )

    op.create_table(
        "requirement_baseline_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("change_summary", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["baseline_id"], ["requirement_baselines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_id", "version", name="uq_requirement_version"),
    )
    with op.batch_alter_table("requirement_baseline_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_baseline_versions_baseline_id"),
            ["baseline_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_baseline_versions_organization_id"),
            ["organization_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requirement_baseline_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_baseline_versions_organization_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_baseline_versions_baseline_id"))

    op.drop_table("requirement_baseline_versions")
    with op.batch_alter_table("requirement_baselines", schema=None) as batch_op:
        batch_op.drop_index("ix_requirement_baselines_project_status")
        batch_op.drop_index(batch_op.f("ix_requirement_baselines_project_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_baselines_organization_id"))

    op.drop_table("requirement_baselines")
    # ### end Alembic commands ###
