"""approvals and work items

Revision ID: dd9a9db68cdb
Revises: b17c387ca429
Create Date: 2026-09-17 12:55:03.569602

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd9a9db68cdb"
down_revision = "b17c387ca429"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("artifact_type", sa.String(length=48), nullable=False),
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_version", sa.Integer(), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decider_id", sa.String(length=255), nullable=False),
        sa.Column("decider_roles", sa.JSON(), nullable=False),
        sa.Column("author_id", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(
            "ix_approvals_artifact", ["artifact_type", "artifact_id"], unique=False
        )
        batch_op.create_index(
            "ix_approvals_org_created", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_approvals_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_approvals_project_id"), ["project_id"], unique=False)

    op.create_table(
        "work_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("acceptance_criteria", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("release_target", sa.String(length=64), nullable=True),
        sa.Column("estimate", sa.String(length=32), nullable=True),
        sa.Column("source_baseline_id", sa.Uuid(), nullable=True),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("is_derived", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["work_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_baseline_id"], ["requirement_baselines.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "code", name="uq_work_items_project_code"),
        sa.UniqueConstraint("project_id", "number", name="uq_work_items_project_number"),
    )
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_work_items_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_work_items_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_work_items_project_id"), ["project_id"], unique=False)
        batch_op.create_index("ix_work_items_project_kind", ["project_id", "kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_work_items_source_baseline_id"), ["source_baseline_id"], unique=False
        )

    op.create_table(
        "work_item_dependencies",
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_id"], ["work_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_item_id"], ["work_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("work_item_id", "depends_on_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("work_item_dependencies")
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_items_source_baseline_id"))
        batch_op.drop_index("ix_work_items_project_kind")
        batch_op.drop_index(batch_op.f("ix_work_items_project_id"))
        batch_op.drop_index(batch_op.f("ix_work_items_parent_id"))
        batch_op.drop_index(batch_op.f("ix_work_items_organization_id"))

    op.drop_table("work_items")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_project_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_organization_id"))
        batch_op.drop_index("ix_approvals_org_created")
        batch_op.drop_index("ix_approvals_artifact")

    op.drop_table("approvals")
    # ### end Alembic commands ###
